FROM node as build
WORKDIR /client
COPY package*.json .
RUN npm install --force
COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build


FROM nginx
COPY --from=build /client/build /usr/share/nginx/html